#++++++++++++++++++++++++++++++++++++++
# Elasticsearch Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   elasticsearch - official Elasticsaerch
#                   https://hub.docker.com/_/elasticsearch/
#
#++++++++++++++++++++++++++++++++++++++

FROM elasticsearch
