#++++++++++++++++++++++++++++++++++++++
# SolR Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   solr - official solr
#                   https://hub.docker.com/_/solr/
#
#++++++++++++++++++++++++++++++++++++++

FROM makuk66/docker-solr:4.10.4 
