# MongoDB 3.4.1 on Nanoserver [ Thin UI Less ]
# Todo : Add Volume for Data store

MAINTAINER ANANT Corporation https://www.anant.us | Report Issues : https://github.com/Appleseed/search-stack/issues

FROM stefanscherer/mongo-windows:nano

 
